//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Entities", "FK_Post_Autor", "Autor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.Autor), "Post", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.Post), true)]
[assembly: EdmRelationshipAttribute("Entities", "FK_Post_Categoria", "Categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.Categoria), "Post", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.Post), true)]
[assembly: EdmRelationshipAttribute("Entities", "FK_Comentario_Post", "Post", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataAccess.Post), "Comentario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.Comentario), true)]

#endregion

namespace DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BlogConnection : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BlogConnection object using the connection string found in the 'BlogConnection' section of the application configuration file.
        /// </summary>
        public BlogConnection() : base("name=BlogConnection", "BlogConnection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlogConnection object.
        /// </summary>
        public BlogConnection(string connectionString) : base(connectionString, "BlogConnection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlogConnection object.
        /// </summary>
        public BlogConnection(EntityConnection connection) : base(connection, "BlogConnection")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Assinantes> Assinantes
        {
            get
            {
                if ((_Assinantes == null))
                {
                    _Assinantes = base.CreateObjectSet<Assinantes>("Assinantes");
                }
                return _Assinantes;
            }
        }
        private ObjectSet<Assinantes> _Assinantes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Autor> Autor
        {
            get
            {
                if ((_Autor == null))
                {
                    _Autor = base.CreateObjectSet<Autor>("Autor");
                }
                return _Autor;
            }
        }
        private ObjectSet<Autor> _Autor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categoria> Categoria
        {
            get
            {
                if ((_Categoria == null))
                {
                    _Categoria = base.CreateObjectSet<Categoria>("Categoria");
                }
                return _Categoria;
            }
        }
        private ObjectSet<Categoria> _Categoria;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comentario> Comentario
        {
            get
            {
                if ((_Comentario == null))
                {
                    _Comentario = base.CreateObjectSet<Comentario>("Comentario");
                }
                return _Comentario;
            }
        }
        private ObjectSet<Comentario> _Comentario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Post> Post
        {
            get
            {
                if ((_Post == null))
                {
                    _Post = base.CreateObjectSet<Post>("Post");
                }
                return _Post;
            }
        }
        private ObjectSet<Post> _Post;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Assinantes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAssinantes(Assinantes assinantes)
        {
            base.AddObject("Assinantes", assinantes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Autor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAutor(Autor autor)
        {
            base.AddObject("Autor", autor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categoria EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategoria(Categoria categoria)
        {
            base.AddObject("Categoria", categoria);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comentario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComentario(Comentario comentario)
        {
            base.AddObject("Comentario", comentario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Post EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPost(Post post)
        {
            base.AddObject("Post", post);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Assinantes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Assinantes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Assinantes object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static Assinantes CreateAssinantes(global::System.Int32 id, global::System.String nome, global::System.String email)
        {
            Assinantes assinantes = new Assinantes();
            assinantes.ID = id;
            assinantes.Nome = nome;
            assinantes.Email = email;
            return assinantes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Data_Nascimento
        {
            get
            {
                return _Data_Nascimento;
            }
            set
            {
                OnData_NascimentoChanging(value);
                ReportPropertyChanging("Data_Nascimento");
                _Data_Nascimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data_Nascimento");
                OnData_NascimentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _Data_Nascimento;
        partial void OnData_NascimentoChanging(Nullable<global::System.DateTime> value);
        partial void OnData_NascimentoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Autor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Autor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Autor object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        public static Autor CreateAutor(global::System.Int32 id, global::System.String nome)
        {
            Autor autor = new Autor();
            autor.ID = id;
            autor.Nome = nome;
            return autor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Post_Autor", "Post")]
        public EntityCollection<Post> Post
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Post>("Entities.FK_Post_Autor", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Post>("Entities.FK_Post_Autor", "Post", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categoria : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categoria object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static Categoria CreateCategoria(global::System.Int32 id)
        {
            Categoria categoria = new Categoria();
            categoria.ID = id;
            return categoria;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Post_Categoria", "Post")]
        public EntityCollection<Post> Post
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Post>("Entities.FK_Post_Categoria", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Post>("Entities.FK_Post_Categoria", "Post", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Comentario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comentario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comentario object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="texto">Initial value of the Texto property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static Comentario CreateComentario(global::System.Int32 id, global::System.String texto, global::System.String nome, global::System.String email)
        {
            Comentario comentario = new Comentario();
            comentario.ID = id;
            comentario.Texto = texto;
            comentario.Nome = nome;
            comentario.Email = email;
            return comentario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Post_Id
        {
            get
            {
                return _Post_Id;
            }
            set
            {
                OnPost_IdChanging(value);
                ReportPropertyChanging("Post_Id");
                _Post_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Post_Id");
                OnPost_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Post_Id;
        partial void OnPost_IdChanging(Nullable<global::System.Int32> value);
        partial void OnPost_IdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Comentario_Post", "Post")]
        public Post Post
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("Entities.FK_Comentario_Post", "Post").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("Entities.FK_Comentario_Post", "Post").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Post> PostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("Entities.FK_Comentario_Post", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Post>("Entities.FK_Comentario_Post", "Post", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Entities", Name="Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Post : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Post object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="autor_Id">Initial value of the Autor_Id property.</param>
        /// <param name="categoria_Id">Initial value of the Categoria_Id property.</param>
        /// <param name="texto">Initial value of the Texto property.</param>
        public static Post CreatePost(global::System.Int32 id, global::System.DateTime data, global::System.Int32 autor_Id, global::System.Int32 categoria_Id, global::System.String texto)
        {
            Post post = new Post();
            post.ID = id;
            post.Data = data;
            post.Autor_Id = autor_Id;
            post.Categoria_Id = categoria_Id;
            post.Texto = texto;
            return post;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.DateTime _Data;
        partial void OnDataChanging(global::System.DateTime value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Autor_Id
        {
            get
            {
                return _Autor_Id;
            }
            set
            {
                OnAutor_IdChanging(value);
                ReportPropertyChanging("Autor_Id");
                _Autor_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Autor_Id");
                OnAutor_IdChanged();
            }
        }
        private global::System.Int32 _Autor_Id;
        partial void OnAutor_IdChanging(global::System.Int32 value);
        partial void OnAutor_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Categoria_Id
        {
            get
            {
                return _Categoria_Id;
            }
            set
            {
                OnCategoria_IdChanging(value);
                ReportPropertyChanging("Categoria_Id");
                _Categoria_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Categoria_Id");
                OnCategoria_IdChanged();
            }
        }
        private global::System.Int32 _Categoria_Id;
        partial void OnCategoria_IdChanging(global::System.Int32 value);
        partial void OnCategoria_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Palavras_Chave
        {
            get
            {
                return _Palavras_Chave;
            }
            set
            {
                OnPalavras_ChaveChanging(value);
                ReportPropertyChanging("Palavras_Chave");
                _Palavras_Chave = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Palavras_Chave");
                OnPalavras_ChaveChanged();
            }
        }
        private global::System.String _Palavras_Chave;
        partial void OnPalavras_ChaveChanging(global::System.String value);
        partial void OnPalavras_ChaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentario_Rodape
        {
            get
            {
                return _Comentario_Rodape;
            }
            set
            {
                OnComentario_RodapeChanging(value);
                ReportPropertyChanging("Comentario_Rodape");
                _Comentario_Rodape = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comentario_Rodape");
                OnComentario_RodapeChanged();
            }
        }
        private global::System.String _Comentario_Rodape;
        partial void OnComentario_RodapeChanging(global::System.String value);
        partial void OnComentario_RodapeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Post_Autor", "Autor")]
        public Autor Autor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Autor>("Entities.FK_Post_Autor", "Autor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Autor>("Entities.FK_Post_Autor", "Autor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Autor> AutorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Autor>("Entities.FK_Post_Autor", "Autor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Autor>("Entities.FK_Post_Autor", "Autor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Post_Categoria", "Categoria")]
        public Categoria Categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("Entities.FK_Post_Categoria", "Categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("Entities.FK_Post_Categoria", "Categoria").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categoria> CategoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categoria>("Entities.FK_Post_Categoria", "Categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categoria>("Entities.FK_Post_Categoria", "Categoria", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Entities", "FK_Comentario_Post", "Comentario")]
        public EntityCollection<Comentario> Comentario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Comentario>("Entities.FK_Comentario_Post", "Comentario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Comentario>("Entities.FK_Comentario_Post", "Comentario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
